[package]
name = "muxdeck-desktop"
version = "0.13.0"
description = "muxdeck desktop app"
edition = "2021"

[lib]
name = "muxdeck_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-notification = "2"
serde_json = "1"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
tauri-plugin-dialog = "2"

[profile.release]
strip = true
lto = true
