[package]
name = "muxdeck-desktop"
version = "0.10.1"
description = "muxdeck desktop app"
edition = "2021"

[lib]
name = "muxdeck_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-notification = "2"

[profile.release]
strip = true
lto = true
